exports.chemicals = [
    {name: "sodium laureth", type: 'sulfate'}, 
    {name: "myreth", type: 'sulfate'}, 
    {name: "lauryl sulfate", type: 'sulfate'},
    {name: "sodium c14-16 olefin sulfonate", type: 'sulfate'},
    {name: "ammonium laureth",  type: 'sulfate'},
    {name: "sodium cocoyl sarcosinate", type: 'sulfate'},
    {name: "alkyl benzene sulfonate", type: 'sulfate'},
    {name: "ammonium", type: 'sulfate'},
    {name: "sodium xylenesulfonate", type: 'sulfate'},
    {name: "ethyl peg-15 cocamine sulfate", type: 'sulfate'},
    {name: "tea-dodecylbenzenesulfonate", type: 'sulfate'},
    {name: "sodium lauryl sulfoacetate", type: 'sulfate'},
    {name: "dioctyl sodium sulfosuccinate", type: 'sulfate'},
    {name: "sodium xylenesulfonate", type: 'sulfate'},
    {name: "amodimethicone", type: 'silicone'},
    {name: "dimethicone", type: 'silicone'},
    {name: "dimethiconol", type: 'silicone'},
    {name: "cyclomethicone", type: 'silicone'},
    {name: "cyclopentasiloxane", type: 'silicone'},
    {name: "behenoxy dimethicone", type: 'silicone'},
    {name: "bis-aminopropyl dimethicone", type: 'silicone'},
    {name: "cetearyl methicone", type: 'silicone'},
    {name: "cetyl dimethicone", type: 'silicone'},
    {name: "phenyl trimethicone", type: 'silicone'},
    {name: "stearyl dimethicone", type: 'silicone'},
    {name: "trimethylsilylamodimethicone", type: 'silicone'},
    {name: "quaternium-15", type: 'formaldehyde'},
    {name: "DMDM hydantoin", type: 'formaldehyde'},
    {name: "imidazolidinyl", type: 'formaldehyde'},
    {name: "diazolidinyl", type: 'formaldehyde'},
    {name: "benzylhemiformal", type: 'formaldehyde'},
]
      
//always search chem. if name found, set problem {chem: name,type: type}